import { ContestEntity } from '@/types/contest';

export function getMockContests(): ContestEntity[] {
  const now = Date.now();
  return [
    {
      id: 'contest-1',
      code: 'START256D',
      slug: 'starters-256-division-4',
      title: 'Starters 256 (Rated for Div 4)',
      description: 'CodeChef style weekly algorithmic challenge rated for beginners and 1-Star coders (Rating < 1400).',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'LIVE',
      startTime: new Date(now - 35 * 60 * 1000).toISOString(), // started 35 mins ago
      endTime: new Date(now + 55 * 60 * 1000).toISOString(), // ends in 55 mins
      durationMinutes: 120,
      problemsCount: 6,
      registeredParticipants: 4280,
      submissionsCount: 12120,
      organizer: 'CodePlatform Division 4 Council',
      bannerColor: '#64748B',
      tags: ['Starters', 'Div 4', 'Rated', 'Beginner'],
      rated: true,
      division: 'Div 4',
      ratingRange: '0 - 1399 (1★)',
      prizePool: 'Rating Points & Ladders',
    },
    {
      id: 'contest-2',
      code: 'START256C',
      slug: 'starters-256-division-3',
      title: 'Starters 256 (Rated for Div 3)',
      description: 'Intermediate rated round for 2-Star coders (1400 <= Rating < 1600). 6 problems covering Greedy, Math, DP.',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'LIVE',
      startTime: new Date(now - 35 * 60 * 1000).toISOString(),
      endTime: new Date(now + 55 * 60 * 1000).toISOString(),
      durationMinutes: 120,
      problemsCount: 6,
      registeredParticipants: 3120,
      submissionsCount: 8940,
      organizer: 'CodePlatform Division 3 Council',
      bannerColor: '#16A34A',
      tags: ['Starters', 'Div 3', 'Rated', 'Intermediate'],
      rated: true,
      division: 'Div 3',
      ratingRange: '1400 - 1599 (2★)',
      prizePool: 'Rating Points & Ladders',
    },
    {
      id: 'contest-3',
      code: 'START256B',
      slug: 'starters-256-division-2',
      title: 'Starters 256 (Rated for Div 2)',
      description: 'Advanced rated contest for 3-Star and 4-Star coders (1600 <= Rating < 2000). Graph, Segment Trees, Hard DP.',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'LIVE',
      startTime: new Date(now - 35 * 60 * 1000).toISOString(),
      endTime: new Date(now + 55 * 60 * 1000).toISOString(),
      durationMinutes: 120,
      problemsCount: 6,
      registeredParticipants: 1850,
      submissionsCount: 4320,
      organizer: 'CodePlatform Division 2 Council',
      bannerColor: '#2563EB',
      tags: ['Starters', 'Div 2', 'Rated', 'Advanced'],
      rated: true,
      division: 'Div 2',
      ratingRange: '1600 - 1999 (3★ & 4★)',
      prizePool: 'Rating Points & Ladders',
    },
    {
      id: 'contest-4',
      code: 'START256A',
      slug: 'starters-256-division-1',
      title: 'Starters 256 (Rated for Div 1)',
      description: 'Premier competitive round for Grandmasters and 5★+ coders (Rating >= 2000).',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'LIVE',
      startTime: new Date(now - 35 * 60 * 1000).toISOString(),
      endTime: new Date(now + 55 * 60 * 1000).toISOString(),
      durationMinutes: 120,
      problemsCount: 6,
      registeredParticipants: 640,
      submissionsCount: 1980,
      organizer: 'CodePlatform Grandmaster Arena',
      bannerColor: '#DC2626',
      tags: ['Starters', 'Div 1', 'Rated', 'Grandmaster'],
      rated: true,
      division: 'Div 1',
      ratingRange: '2000+ (5★ - 7★)',
      prizePool: '$2,500 Cash & Trophies',
    },
    {
      id: 'contest-5',
      code: 'FACULTY-EVAL-2',
      slug: 'cs301-mid-term-dsa-benchmarking',
      title: 'CS301: Mid-Term DSA Benchmarking Assessment',
      description: 'Faculty-monitored institutional test covering Graph Traversal, Binary Search, and Dynamic Programming.',
      scope: 'Internal Faculty Assessment',
      scoringFormat: 'IOI (Partial Subtasks)',
      status: 'UPCOMING',
      startTime: new Date(now + 7 * 24 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now + 7 * 24 * 60 * 60 * 1000 + 120 * 60 * 1000).toISOString(),
      durationMinutes: 120,
      problemsCount: 5,
      registeredParticipants: 450,
      submissionsCount: 0,
      organizer: 'Department of Computer Science',
      bannerColor: '#D97706',
      tags: ['Exam', 'University', 'Strict Proctored'],
      rated: false,
    },
    {
      id: 'contest-7',
      code: 'GLOBAL-341',
      slug: 'codeplatform-weekly-contest-341',
      title: 'CodePlatform Weekly Competitive Contest 341',
      description: 'Weekly algorithmic challenge. 4 problems: Bitmasking, Dijkstra, Two Pointers, and Segment Trees.',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'PAST',
      startTime: new Date(now - 7 * 24 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now - 7 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
      durationMinutes: 90,
      problemsCount: 4,
      registeredParticipants: 3120,
      submissionsCount: 9480,
      organizer: 'CodePlatform Official',
      bannerColor: '#475569',
      tags: ['Algorithms', 'Weekly', 'Archived'],
      rated: true,
    },
    {
      id: 'contest-6',
      code: 'INST-OLYMPIAD-09',
      slug: 'national-coding-olympiad-prelims',
      title: 'National Coding Olympiad Prelims 2026',
      description: 'Invitational contest designed for competitive coders qualifying for National IOI camps.',
      scope: 'Institutional Invitational',
      scoringFormat: 'IOI (Partial Subtasks)',
      status: 'PAST',
      startTime: new Date(now - 14 * 24 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now - 14 * 24 * 60 * 60 * 1000 + 180 * 60 * 1000).toISOString(),
      durationMinutes: 180,
      problemsCount: 6,
      registeredParticipants: 1890,
      submissionsCount: 5210,
      organizer: 'National Olympiad Committee',
      bannerColor: '#475569',
      tags: ['IOI', 'Olympiad', 'Archived'],
      rated: true,
    },
  ];
}

export const MOCK_CONTESTS: ContestEntity[] = getMockContests();

export function getContestByIdOrSlug(idOrSlug: string): ContestEntity | undefined {
  return MOCK_CONTESTS.find(
    (c) => c.id === idOrSlug || c.slug === idOrSlug || c.code.toLowerCase() === idOrSlug.toLowerCase()
  );
}
