packages:
  - 'server'
  - 'client'

allowBuilds:
  '@apollo/protobufjs': true
  '@firebase/util': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  'bcryptjs': true
  'esbuild': true
  'msgpackr-extract': true
  'prisma': true
  protobufjs: true
  'unrs-resolver': true
  'workerd': false
