import { ContestEntity } from '@/types/contest';

export function getMockContests(): ContestEntity[] {
  const now = Date.now();
  return [
    {
      id: 'contest-1',
      code: 'GLOBAL-342',
      slug: 'codeplatform-weekly-contest-342',
      title: 'CodePlatform Weekly Competitive Contest 342',
      description: 'Weekly algorithmic challenge featuring 4 problems ranging from Easy to Hard. Rated for all divisions.',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'LIVE',
      startTime: new Date(now - 35 * 60 * 1000).toISOString(), // started 35 mins ago
      endTime: new Date(now + 55 * 60 * 1000).toISOString(), // ends in 55 mins
      durationMinutes: 90,
      problemsCount: 4,
      registeredParticipants: 2840,
      submissionsCount: 7120,
      organizer: 'CodePlatform Official',
      bannerColor: '#2563EB',
      tags: ['Algorithms', 'Rated', 'Weekly', 'Global'],
      rated: true,
      prizePool: '$1,500 Amazon Gift Cards',
    },
    {
      id: 'contest-2',
      code: 'ICPC-INST-04',
      slug: 'inter-institute-programming-invitational-iv',
      title: 'Inter-Institute Programming Invitational IV',
      description: 'Official ICPC format team contest for university students. 10 problems, strict penalty time evaluation.',
      scope: 'Institute League',
      scoringFormat: 'ICPC (Penalty Time)',
      status: 'UPCOMING',
      startTime: new Date(now + 2 * 24 * 60 * 60 * 1000).toISOString(), // in 2 days
      endTime: new Date(now + 2 * 24 * 60 * 60 * 1000 + 300 * 60 * 1000).toISOString(),
      durationMinutes: 300,
      problemsCount: 10,
      registeredParticipants: 1420,
      submissionsCount: 0,
      organizer: 'ACM Chapter & Faculty Guild',
      bannerColor: '#7C3AED',
      tags: ['ICPC', 'Teams', 'Institute', 'Advanced'],
      rated: true,
      prizePool: '$5,000 Trophy & Sponsor Badges',
    },
    {
      id: 'contest-3',
      code: 'BIWEEKLY-112',
      slug: 'biweekly-speed-run-112',
      title: 'Biweekly Speed Run #112',
      description: 'Fast-paced 60-minute programming sprint focusing on Arrays, Strings, and Greedy optimization.',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'UPCOMING',
      startTime: new Date(now + 5 * 24 * 60 * 60 * 1000).toISOString(), // in 5 days
      endTime: new Date(now + 5 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
      durationMinutes: 60,
      problemsCount: 4,
      registeredParticipants: 980,
      submissionsCount: 0,
      organizer: 'SpeedRun League',
      bannerColor: '#0EA5E9',
      tags: ['SpeedRun', 'Short', 'Rated'],
      rated: true,
    },
    {
      id: 'contest-4',
      code: 'FACULTY-EVAL-2',
      slug: 'cs301-mid-term-dsa-benchmarking',
      title: 'CS301: Mid-Term DSA Benchmarking Assessment',
      description: 'Faculty-monitored institutional test covering Graph Traversal, Binary Search, and Dynamic Programming.',
      scope: 'Internal Faculty Assessment',
      scoringFormat: 'IOI (Partial Subtasks)',
      status: 'UPCOMING',
      startTime: new Date(now + 7 * 24 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now + 7 * 24 * 60 * 60 * 1000 + 120 * 60 * 1000).toISOString(),
      durationMinutes: 120,
      problemsCount: 5,
      registeredParticipants: 450,
      submissionsCount: 0,
      organizer: 'Department of Computer Science',
      bannerColor: '#D97706',
      tags: ['Exam', 'University', 'Strict Proctored'],
      rated: false,
    },
    {
      id: 'contest-5',
      code: 'GLOBAL-341',
      slug: 'codeplatform-weekly-contest-341',
      title: 'CodePlatform Weekly Competitive Contest 341',
      description: 'Weekly algorithmic challenge. 4 problems: Bitmasking, Dijkstra, Two Pointers, and Segment Trees.',
      scope: 'Global',
      scoringFormat: 'LeetCode (Score + Penalty)',
      status: 'PAST',
      startTime: new Date(now - 7 * 24 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now - 7 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
      durationMinutes: 90,
      problemsCount: 4,
      registeredParticipants: 3120,
      submissionsCount: 9480,
      organizer: 'CodePlatform Official',
      bannerColor: '#475569',
      tags: ['Algorithms', 'Weekly', 'Archived'],
      rated: true,
    },
    {
      id: 'contest-6',
      code: 'INST-OLYMPIAD-09',
      slug: 'national-coding-olympiad-prelims',
      title: 'National Coding Olympiad Prelims 2026',
      description: 'Invitational contest designed for competitive coders qualifying for National IOI camps.',
      scope: 'Institutional Invitational',
      scoringFormat: 'IOI (Partial Subtasks)',
      status: 'PAST',
      startTime: new Date(now - 14 * 24 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now - 14 * 24 * 60 * 60 * 1000 + 180 * 60 * 1000).toISOString(),
      durationMinutes: 180,
      problemsCount: 6,
      registeredParticipants: 1890,
      submissionsCount: 5210,
      organizer: 'National Olympiad Committee',
      bannerColor: '#475569',
      tags: ['IOI', 'Olympiad', 'Archived'],
      rated: true,
    },
  ];
}

export const MOCK_CONTESTS: ContestEntity[] = getMockContests();
