import { CourseDirectoryEntity } from '@/types/course';

export const MOCK_COURSES: CourseDirectoryEntity[] = [
  {
    id: 'course-1',
    code: 'DSA-301',
    slug: 'advanced-data-structures-algorithms',
    title: 'Advanced Data Structures & Algorithmic Optimization',
    category: 'Computer Science & DSA',
    level: 'Intermediate',
    instructorName: 'Prof. Ananya Sen',
    instructorTitle: 'Chair of Computer Science',
    institutionName: 'IIT Bombay & ACM Faculty',
    durationHours: 42,
    modulesCount: 6,
    lessonsCount: 28,
    enrolledStudents: 1420,
    completionRate: 68,
    status: 'Published',
    tags: ['DSA', 'Trees', 'Dynamic Programming', 'Graphs'],
    description: 'Master advanced trees (AVL, Red-Black), Segment Trees, Fenwick Trees, Tarjan BFS/DFS, and dynamic programming state optimizations.',
    accentColor: '#2563EB',
    moduleHighlights: [
      { title: 'Segment Trees & Lazy Propagation', lessons: 5 },
      { title: 'Dynamic Programming on Trees & DAGs', lessons: 6 },
      { title: 'Network Flow & Bipartite Matching', lessons: 4 },
    ],
    levels: [
      {
        levelNumber: 1,
        levelTitle: 'Tree Decompositions & Segment Trees',
        badgeTagline: 'Core Mastery',
        summary: 'Range queries and range updates in logarithmic time.',
        estimatedWeeks: 3,
        modules: [
          {
            id: 'mod-1',
            title: 'Segment Tree Construction & Point Updates',
            subtitle: 'O(n) build and O(log n) update operations.',
            problemsCount: 4,
            topics: ['Range Sum', 'Range Min/Max', 'Point Update'],
            status: 'Completed',
          },
          {
            id: 'mod-2',
            title: 'Lazy Propagation for Range Updates',
            subtitle: 'Postponing updates to children nodes until required.',
            problemsCount: 5,
            topics: ['Lazy Tags', 'Range Addition', 'Segment Tree Beating'],
            status: 'In Progress',
          },
        ],
      },
      {
        levelNumber: 2,
        levelTitle: 'Graph Theory & Disjoint Sets',
        badgeTagline: 'Advanced Flow',
        summary: 'Strongly connected components, Euler tours, and Heavy-Light Decomposition.',
        estimatedWeeks: 4,
        modules: [
          {
            id: 'mod-3',
            title: 'Tarjan & Kosaraju SCC Algorithms',
            subtitle: 'Condensing directed graphs into DAGs.',
            problemsCount: 4,
            topics: ['Low-link Values', 'DFS Spanning Tree', '2-SAT'],
            status: 'Not Started',
          },
        ],
      },
    ],
  },
  {
    id: 'course-2',
    code: 'SYS-402',
    slug: 'distributed-systems-cloud-architecture',
    title: 'Distributed Systems & Scalable Cloud Architecture',
    category: 'System Design & Architecture',
    level: 'Advanced',
    instructorName: 'Dr. Michael Chen',
    instructorTitle: 'Principal Cloud Architect',
    institutionName: 'Stanford Engineering Lab',
    durationHours: 36,
    modulesCount: 5,
    lessonsCount: 22,
    enrolledStudents: 980,
    completionRate: 45,
    status: 'Published',
    tags: ['System Design', 'Kafka', 'Raft', 'Microservices', 'PostgreSQL'],
    description: 'Design fault-tolerant distributed systems, consensus algorithms (Paxos, Raft), database sharding, and high-throughput streaming pipelines.',
    accentColor: '#7C3AED',
    moduleHighlights: [
      { title: 'Consensus Protocols (Raft & Paxos)', lessons: 5 },
      { title: 'Distributed Caching & Sharding', lessons: 4 },
      { title: 'Event-Driven Architectures with Kafka', lessons: 5 },
    ],
  },
  {
    id: 'course-3',
    code: 'CP-201',
    slug: 'competitive-programming-number-theory',
    title: 'Competitive Programming: Math & Number Theory Mastery',
    category: 'Competitive Programming',
    level: 'Intermediate',
    instructorName: 'Coach Alexander Vance',
    instructorTitle: 'Grandmaster / ICPC World Finalist',
    institutionName: 'CodePlatform Competitive Cell',
    durationHours: 28,
    modulesCount: 4,
    lessonsCount: 18,
    enrolledStudents: 2150,
    completionRate: 85,
    status: 'Published',
    tags: ['Math', 'Modular Arithmetic', 'Combinatorics', 'FFT', 'Matrix Exponentiation'],
    description: 'Fast I/O, Modular inverses, Chinese Remainder Theorem, Fermat Little Theorem, Fast Fourier Transform, and Matrix Multiplication algorithms.',
    accentColor: '#059669',
    moduleHighlights: [
      { title: 'Modular Arithmetic & Fermat Inverses', lessons: 4 },
      { title: 'Combinatorics & Lucas Theorem', lessons: 4 },
      { title: 'Fast Fourier Transform (FFT) Polynomial Mult', lessons: 5 },
    ],
  },
  {
    id: 'course-4',
    code: 'WEB-301',
    slug: 'fullstack-nextjs-enterprise-microservices',
    title: 'Enterprise Full-Stack Architecture with Next.js & NestJS',
    category: 'Web & Full-Stack Development',
    level: 'Intermediate',
    instructorName: 'Priya Sharma',
    instructorTitle: 'Lead Software Architect',
    institutionName: 'TechGuild Bangalore',
    durationHours: 32,
    modulesCount: 5,
    lessonsCount: 24,
    enrolledStudents: 1680,
    completionRate: 52,
    status: 'Published',
    tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Prisma', 'Docker'],
    description: 'Production-ready full-stack applications with React Server Components, Tailwind CSS, NestJS microservices, Redis queues, and Docker sandboxes.',
    accentColor: '#0EA5E9',
    moduleHighlights: [
      { title: 'Next.js App Router & SSR Boundaries', lessons: 5 },
      { title: 'NestJS Microservices & BullMQ', lessons: 5 },
      { title: 'Database Optimization with Prisma & Postgres', lessons: 4 },
    ],
  },
  {
    id: 'course-5',
    code: 'AI-501',
    slug: 'applied-machine-learning-deep-learning',
    title: 'Applied Machine Learning & Neural Network Foundations',
    category: 'AI, ML & Data Science',
    level: 'Advanced',
    instructorName: 'Dr. Robert Zimmerman',
    instructorTitle: 'AI Research Director',
    institutionName: 'MIT AI Lab',
    durationHours: 48,
    modulesCount: 6,
    lessonsCount: 30,
    enrolledStudents: 1250,
    completionRate: 38,
    status: 'Published',
    tags: ['PyTorch', 'Transformers', 'Backpropagation', 'CNNs', 'LLMs'],
    description: 'Build neural networks from scratch, implement transformers, optimize backpropagation with PyTorch, and fine-tune open-source LLMs.',
    accentColor: '#D97706',
    moduleHighlights: [
      { title: 'Neural Networks & Gradient Descent from Scratch', lessons: 6 },
      { title: 'Transformer Architecture & Self-Attention', lessons: 6 },
      { title: 'Fine-Tuning & Model Deployment', lessons: 5 },
    ],
  },
];
