export interface LeaderboardRankEntity {
  id: string;
  rank: number;
  handle: string;
  name: string;
  avatar: string;
  country: string;
  countryCode: string;
  institution: string;
  rating: number;
  ratingTier: 'Grandmaster' | 'Master' | 'Candidate Master' | 'Expert' | 'Specialist';
  tierColor: string;
  problemsSolved: number;
  contestsAttended: number;
  globalPercentile: string;
  streakDays: number;
  badge: string;
}

export const MOCK_LEADERBOARD: LeaderboardRankEntity[] = [
  {
    id: 'rank-1',
    rank: 1,
    handle: 'algotitan',
    name: 'Alex Morgan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    country: 'Poland',
    countryCode: 'PL',
    institution: 'Warsaw Institute of Tech',
    rating: 3120,
    ratingTier: 'Grandmaster',
    tierColor: '#EF4444',
    problemsSolved: 620,
    contestsAttended: 48,
    globalPercentile: 'Top 0.01%',
    streakDays: 142,
    badge: '👑 Global #1',
  },
  {
    id: 'rank-2',
    rank: 2,
    handle: 'hypercoder',
    name: 'Jordan Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    country: 'United States',
    countryCode: 'US',
    institution: 'MIT',
    rating: 2980,
    ratingTier: 'Grandmaster',
    tierColor: '#EF4444',
    problemsSolved: 585,
    contestsAttended: 42,
    globalPercentile: 'Top 0.03%',
    streakDays: 98,
    badge: '🥈 Global #2',
  },
  {
    id: 'rank-3',
    rank: 3,
    handle: 'matrix_master',
    name: 'David Zhang',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    country: 'China',
    countryCode: 'CN',
    institution: 'Tsinghua University',
    rating: 2915,
    ratingTier: 'Grandmaster',
    tierColor: '#EF4444',
    problemsSolved: 560,
    contestsAttended: 39,
    globalPercentile: 'Top 0.05%',
    streakDays: 110,
    badge: '🥉 Global #3',
  },
  {
    id: 'rank-4',
    rank: 4,
    handle: 'alex_weber',
    name: 'Alexander Weber',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    country: 'Germany',
    countryCode: 'DE',
    institution: 'TU Munich',
    rating: 2740,
    ratingTier: 'Master',
    tierColor: '#F59E0B',
    problemsSolved: 512,
    contestsAttended: 35,
    globalPercentile: 'Top 0.12%',
    streakDays: 64,
    badge: '⭐ International Master',
  },
  {
    id: 'rank-5',
    rank: 5,
    handle: 'arjun_sharma',
    name: 'Arjun Sharma',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    country: 'India',
    countryCode: 'IN',
    institution: 'IIT Bombay',
    rating: 2680,
    ratingTier: 'Master',
    tierColor: '#F59E0B',
    problemsSolved: 495,
    contestsAttended: 31,
    globalPercentile: 'Top 0.25%',
    streakDays: 85,
    badge: '⭐ Master',
  },
  {
    id: 'rank-6',
    rank: 6,
    handle: 'samir_sen',
    name: 'Samir Sen',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    country: 'India',
    countryCode: 'IN',
    institution: 'Heritage Institute of Technology',
    rating: 2380,
    ratingTier: 'Master',
    tierColor: '#F59E0B',
    problemsSolved: 342,
    contestsAttended: 24,
    globalPercentile: 'Top 0.85%',
    streakDays: 48,
    badge: '🚀 Institute Master',
  },
  {
    id: 'rank-7',
    rank: 7,
    handle: 'yuki_tanaka',
    name: 'Yuki Tanaka',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    country: 'Japan',
    countryCode: 'JP',
    institution: 'University of Tokyo',
    rating: 2310,
    ratingTier: 'Master',
    tierColor: '#F59E0B',
    problemsSolved: 380,
    contestsAttended: 28,
    globalPercentile: 'Top 1.15%',
    streakDays: 42,
    badge: '⭐ Master',
  },
  {
    id: 'rank-8',
    rank: 8,
    handle: 'elena_rostova',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    country: 'Russia',
    countryCode: 'RU',
    institution: 'MIPT Moscow',
    rating: 2240,
    ratingTier: 'Candidate Master',
    tierColor: '#8B5CF6',
    problemsSolved: 320,
    contestsAttended: 22,
    globalPercentile: 'Top 1.6%',
    streakDays: 31,
    badge: 'Candidate Master',
  },
  {
    id: 'rank-9',
    rank: 9,
    handle: 'marcus_vance',
    name: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    countryCode: 'GB',
    institution: 'Cambridge University',
    rating: 2090,
    ratingTier: 'Expert',
    tierColor: '#3B82F6',
    problemsSolved: 280,
    contestsAttended: 19,
    globalPercentile: 'Top 2.8%',
    streakDays: 25,
    badge: 'Expert',
  },
  {
    id: 'rank-10',
    rank: 10,
    handle: 'priya_nair',
    name: 'Priya Nair',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    country: 'India',
    countryCode: 'IN',
    institution: 'IIT Delhi',
    rating: 1980,
    ratingTier: 'Expert',
    tierColor: '#3B82F6',
    problemsSolved: 265,
    contestsAttended: 18,
    globalPercentile: 'Top 4.2%',
    streakDays: 37,
    badge: 'Expert',
  },
];
